# Generated by Django 4.1.7 on 2023-03-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_likeclouds_cloud_likeclouds_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeclouds',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.cloud'),
        ),
    ]
