# Generated by Django 4.1.7 on 2023-03-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_likeclouds_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareclouds',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cloud'),
        ),
    ]
