# Generated by Django 4.1.7 on 2023-03-06 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_shareclouds_reciever'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareblogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cloud'),
        ),
    ]
