# Generated by Django 4.1.7 on 2023-03-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_shareblogs_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareclouds',
            name='cloud',
        ),
        migrations.AlterField(
            model_name='shareblogs',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.blog'),
        ),
    ]
