# Generated by Django 4.1.7 on 2023-03-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_shareclouds_cloud_alter_shareblogs_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
