# Generated by Django 4.1.7 on 2023-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_cloud_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
