# Generated by Django 4.1.7 on 2023-03-22 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0014_blog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareblogs',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='shareblogs',
            name='community',
        ),
        migrations.RemoveField(
            model_name='shareclouds',
            name='community',
        ),
        migrations.AddField(
            model_name='shareblogs',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recieve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shareblogs',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.blog'),
        ),
        migrations.AlterField(
            model_name='shareclouds',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recievercloud', to=settings.AUTH_USER_MODEL),
        ),
    ]
